### ISSUE TITLE
Tooling expects cql to exist under input/pagecontent/cql

### ISSUE THREAD

**Issue by mholck** [cqframework/cqf-tooling#95]
If the cql folder is not under input/pagecontent the tooling will break and not be able to refresh or bundle the measure packages. 

08:30:55.335 [main] WARN  org.opencds.cqf.utilities.LogUtils - IGProcessor.publishIG - refreshIG
Exception in thread "main" java.lang.RuntimeException: Convention requires the following directory:input/pagecontent/cql/
	at org.opencds.cqf.processor.IGProcessor.ensureDirectory(IGProcessor.java:210)
	at org.opencds.cqf.processor.IGProcessor.ensure(IGProcessor.java:171)
	at org.opencds.cqf.processor.IGRefreshProcessor.refreshIG(IGRefreshProcessor.java:50)
	at org.opencds.cqf.processor.IGProcessor.publishIG(IGProcessor.java:78)
	at org.opencds.cqf.operation.RefreshIGOperation.execute(RefreshIGOperation.java:23)
	at org.opencds.cqf.Main.main(Main.java:141)

we should be able to specify the cql directory rather than look for it in a hard coded location

**Comment by c-schuler** [comment]
I believe this has been addressed. @Chris0296 please verify.

**Comment by Chris0296** [comment]
@c-schuler I have been able to replicate this issue so it may require further work.

**Comment by c-schuler** [comment]
Also see #469
